services:
  reportes-api:
    build:
      context: .     
      dockerfile: Dockerfile
    env_file:
      - .env
    volumes:
      - ./uploads:/app/uploads 
      - ./data:/app/data 
    ports:
      - "3000:3000" 
    restart: always